PERSIAPAN DATA

In [10]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

df_train = pd.read_csv('data_training.csv')
df_test = pd.read_csv('data_testing.csv')

test_ids = df_test['Id']

In [8]:
df_train = pd.read_csv('data_training.csv')
df_test = pd.read_csv('data_testing.csv')

# AMBIL ID DI SINI SEBELUM KOLOMNYA DIHAPUS
test_ids = df_test['Id']

PEMBERSIHAN DATA

In [11]:
# Menangani missing values dengan median
df_train = df_train.fillna(df_train.median())
df_test = df_test.fillna(df_test.median())

# Memisahkan fitur (X) dan target (y) untuk training
# Hapus 'quality' karena itu target, dan 'Id' karena tidak digunakan dalam modeling
X = df_train.drop(['quality', 'Id'], axis=1)
y = df_train['quality']

# Menyiapkan fitur untuk data testing (hapus 'Id' saja)
X_test_final = df_test.drop(['Id'], axis=1)

# Feature Scaling agar rentang nilai kimiawi seragam
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X) # Fit pada data training
X_test_final_scaled = scaler.transform(X_test_final) # Gunakan scaler yang sama untuk data testing

PEMBUATAN MODEL DAN EVALUASI

In [18]:
# Membagi data untuk validasi internal (80% training, 20% validasi)
X_train, X_val, y_train, y_val = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Training Model, disini saya menggunakan random forest
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Cek Akurasi pada data validasi internal
val_preds = model.predict(X_val)
print(f"Akurasi Model: {accuracy_score(y_val, val_preds)}")
print("\nConfusion Matrix:\n", confusion_matrix(y_val, y_pred_val))

final_predictions = model.predict(X_test_final_scaled)

Akurasi Model: 0.5813953488372093

Confusion Matrix:
 [[ 0  1  2  0  0]
 [ 0 42 25  0  0]
 [ 0 23 49  6  0]
 [ 0  2 10  9  0]
 [ 0  0  0  3  0]]


PREDIKSI DATA UJI

In [13]:
df_hasil = pd.DataFrame({
    'Id': test_ids,
    'quality': final_predictions
})

df_hasil.to_csv('hasilprediksi_017.csv', index=False)